"""add trade checklist

Revision ID: 02b723858bcf
Revises: b8169a492cfd
Create Date: 2026-03-06 02:50:02.066950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02b723858bcf'
down_revision: Union[str, Sequence[str], None] = 'b8169a492cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradechecklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_idea_id', sa.Integer(), nullable=False),
    sa.Column('target_verified', sa.Boolean(), nullable=False),
    sa.Column('invalidation_clear', sa.Boolean(), nullable=False),
    sa.Column('risk_acceptable', sa.Boolean(), nullable=False),
    sa.Column('bias_challenged', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_idea_id'], ['tradeidea.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_idea_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tradechecklist')
    # ### end Alembic commands ###
