"""initial schema

Revision ID: 3f54fd2e05ea
Revises: 
Create Date: 2026-03-06 02:38:08.576832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f54fd2e05ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradeidea',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('invalidation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thesis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradeidea_user_id'), 'tradeidea', ['user_id'], unique=False)
    op.create_table('journalentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trade_idea_id', sa.Integer(), nullable=True),
    sa.Column('expected_behaviour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actual_behaviour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thesis_validity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('should_have_skipped', sa.Boolean(), nullable=False),
    sa.Column('lesson_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_idea_id'], ['tradeidea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journalentry_user_id'), 'journalentry', ['user_id'], unique=False)
    op.create_table('tradeideaversion',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('invalidation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thesis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_idea_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_idea_id'], ['tradeidea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradeideaversion_user_id'), 'tradeideaversion', ['user_id'], unique=False)
    op.create_table('approvalevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_idea_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_idea_id'], ['tradeidea.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['tradeideaversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executionticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_event_id', sa.Integer(), nullable=False),
    sa.Column('adapter_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_event_id'], ['approvalevent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executionticket')
    op.drop_table('approvalevent')
    op.drop_index(op.f('ix_tradeideaversion_user_id'), table_name='tradeideaversion')
    op.drop_table('tradeideaversion')
    op.drop_index(op.f('ix_journalentry_user_id'), table_name='journalentry')
    op.drop_table('journalentry')
    op.drop_index(op.f('ix_tradeidea_user_id'), table_name='tradeidea')
    op.drop_table('tradeidea')
    # ### end Alembic commands ###
