"""add market note

Revision ID: b8169a492cfd
Revises: 3f54fd2e05ea
Create Date: 2026-03-06 02:46:12.332437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8169a492cfd'
down_revision: Union[str, Sequence[str], None] = '3f54fd2e05ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_levels', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resistance_levels', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketnote_user_id'), 'marketnote', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketnote_user_id'), table_name='marketnote')
    op.drop_table('marketnote')
    # ### end Alembic commands ###
